Repository cse110-sp24-group2/cse110-sp24-group2, pull requests merged in 2024-06, with the labels that each got.

#84 Notes frontend
  docs/components_TodoList.js.html
  docs/global.html
  source/Notes/index.html
  source/Notes/styles.css
  source/calendar/calendar-styles.css
  source/components/TodoList.js
Labels: enhancement

#73 Create ESLint-CICD ADR
  specs/adr/ESLint-CICD
Labels: documentation, medium priority

#102 syncing colors of calendar and notes with a month
  docs/Notes_app.js.html
  docs/global.html
  source/Notes/app.js
  source/Notes/styles.css
  source/calendar/calendar-styles.css
Labels: enhancement, frontend

#115 Fixed todo overflow and one row todo
  docs/components_TodoList.js.html
  source/Notes/index.html
  source/Notes/styles.css
  source/calendar/calendar-styles.css
  source/components/TodoList.js
Labels: frontend

#123 Changed functionality of searchPage
  docs/global.html
  docs/searchPage_searchPage.js.html
  source/searchPage/searchPage-styles.css
  source/searchPage/searchPage.js
Labels: enhancement, sprint-2, backend

#132 fixing "back to calendar" buttons style
  source/Notes/styles.css
Labels: enhancement, frontend

#155 working animation with old days
  __tests__/e2e/calendar.test.js
  docs/Notes_app.js.html
  docs/calendar_calendar-script.js.html
  docs/components_TodoList.js.html
  docs/global.html
  source/Notes/app.js
  source/Notes/styles.css
  source/calendar/calendar-script.js
  source/calendar/calendar-styles.css
  source/components/TodoList.js
Labels: enhancement, sprint-2

#156 fixed margins of todo list and calendar
  docs/components_TodoList.js.html
  docs/global.html
  source/calendar/calendar-styles.css
  source/components/TodoList.js
Labels: bug, enhancement, frontend

#147 Labels deletion fix
  docs/Notes_app.js.html
  docs/Notes_label.js.html
  docs/global.html
  source/Notes/app.js
  source/Notes/label.js
Labels: bug

#162 added logo and fixed day-names alignment
  assets/icons/icon.ico
  docs/Notes_app.js.html
  docs/global.html
  source/Notes/app.js
  source/Notes/styles.css
  source/calendar/calendar-styles.css
  source/calendar/index.html
  source/main.js
Labels: enhancement, frontend

#175 Tabindex
  docs/Notes_label.js.html
  docs/components_TodoList.js.html
  docs/global.html
  docs/searchPage_searchPage.js.html
  package-lock.json
  source/Notes/label.js
  source/components/TodoList.js
  source/searchPage/searchPage.js
Labels: enhancement

#181 Label text changes color according to background
  docs/Notes_label.js.html
  source/Notes/label.js
Labels: enhancement, frontend, sprint-2

#182 Search page testing
  __tests__/e2e/searchPage.test.js
  package.json
Labels: sprint-2, high priority

#185 frontend modifications (font, button sizes)
  docs/components_TodoList.js.html
  docs/global.html
  source/Notes/index.html
  source/Notes/styles.css
  source/calendar/calendar-styles.css
  source/calendar/index.html
  source/components/TodoList.js
Labels: enhancement, frontend, sprint-2

#203 Update summary.md
  admin/requirements/UMLDiagram.png
  admin/requirements/brainstorming.png
  admin/requirements/summary.md
  admin/requirements/userFlowDiagram.png
  admin/requirements/userPersonas.png
  admin/requirements/wireframes.png
Labels: documentation
